// Package warehouse keeps pallets, and its tables come from its description.
//
// One description does four jobs here. It decodes and encodes the wire; it
// derives what a caller supplies to create a pallet and what a caller supplies
// to change one; and it says which tables hold it. So a column that changed
// would change all four together, which is the whole reason there is one
// description rather than four.
//
// A pallet is an aggregate, not a row. The items on it are entities -- they have
// identities of their own -- so they get a table of their own and a reference
// back. The warehouse a pallet sits in is a plain value and lives in the
// pallet's row.
package warehouse

import (
	"time"

	"github.com/mbauer83/effect-golang-schema/schema"
	"github.com/mbauer83/effect-golang-schema/schema/dynamic"
)

// Item is one thing on a pallet. It has an identity, so it is a thing rather
// than a part.
type Item struct {
	ID       string
	SKU      string
	Quantity int32
}

// ItemSchema describes an item.
//
// The identity is the application's -- a UUID it generates -- so it is Identity
// without Computed, and a caller creating a pallet supplies it. That is the
// distinction Identity and Computed compose to make.
var ItemSchema = schema.Struct[Item]("PalletItem",
	schema.FieldOf("id", schema.UUID().Check(schema.MaxLength(36)),
		func(item Item) string { return item.ID },
		func(item *Item, value string) { item.ID = value }).
		Identity().
		WithDescription("ID is the item's own, generated by whoever puts it on the pallet."),
	schema.FieldOf("sku", schema.Text().Check(schema.MinLength(1)),
		func(item Item) string { return item.SKU },
		func(item *Item, value string) { item.SKU = value }),
	schema.FieldOf("quantity", schema.Int32().Check(schema.AtLeast[int32](1)),
		func(item Item) int32 { return item.Quantity },
		func(item *Item, value int32) { item.Quantity = value }),
).WithDescription("PalletItem is one line of what a pallet holds.")

// Pallet is the aggregate root.
type Pallet struct {
	ID        int64
	Reference string
	Warehouse string
	Items     []Item
	StoredAt  time.Time
}

// PalletSchema describes a pallet.
//
// The identity is the database's, so it is Identity and Computed together and a
// caller creating a pallet does not supply it. StoredAt is Computed with a
// default, which is the other half a projection to storage needs: Computed says
// the value is not the caller's, and the default says what produces it.
var PalletSchema = schema.Struct[Pallet]("Pallet",
	schema.FieldOf("id", schema.Int64(),
		func(pallet Pallet) int64 { return pallet.ID },
		func(pallet *Pallet, value int64) { pallet.ID = value }).
		Identity().
		Computed().
		WithDescription("ID is assigned when the pallet is first stored."),
	schema.FieldOf("reference", schema.Text().Check(schema.MinLength(1), schema.MaxLength(32)),
		func(pallet Pallet) string { return pallet.Reference },
		func(pallet *Pallet, value string) { pallet.Reference = value }).
		WithDescription("Reference is what the label says."),
	schema.FieldOf("warehouse", schema.Text().Check(schema.MinLength(1)),
		func(pallet Pallet) string { return pallet.Warehouse },
		func(pallet *Pallet, value string) { pallet.Warehouse = value }).
		WithDescription("Warehouse is where it sits. A plain value, so it lives in this row."),
	schema.FieldOf("items", schema.List(ItemSchema),
		func(pallet Pallet) []Item { return pallet.Items },
		func(pallet *Pallet, value []Item) { pallet.Items = value }).
		WithDescription("Items are entities, so they get a table of their own."),
	schema.FieldOf("storedAt", schema.Time(),
		func(pallet Pallet) time.Time { return pallet.StoredAt },
		func(pallet *Pallet, value time.Time) { pallet.StoredAt = value }).
		Computed().
		WithDefaultNow().
		WithDescription("StoredAt is when it arrived, which the database records."),
).WithDescription("Pallet is a pallet in a warehouse, with what is on it.")

// Receipt is what a database hands back about a pallet it has just taken: the
// key it assigned, and whether the moment it records was recorded.
//
// Not the instant itself, because how a timestamp comes back is the driver's
// business and differs -- one hands back an instant and another the text it
// stored. What the description claims is that the column has a value without
// anybody supplying one, and that is what this asks.
type Receipt struct {
	ID      int64
	HasDate int64
}

// ReceiptSchema reads the key and whether the default applied.
var ReceiptSchema = schema.Struct[Receipt]("Stored",
	schema.FieldOf("id", schema.Int64(),
		func(receipt Receipt) int64 { return receipt.ID },
		func(receipt *Receipt, value int64) { receipt.ID = value }),
	// An integer and not a boolean, because a driver spells a truth value in
	// whatever its database has: SQLite has no boolean and hands back nought
	// or one, which is exactly what this module's own SQLite dialect says when
	// it maps a boolean column to an integer.
	schema.FieldOf("dated", schema.Int64(),
		func(receipt Receipt) int64 { return receipt.HasDate },
		func(receipt *Receipt, value int64) { receipt.HasDate = value }),
)

// Tally is one number a query returned.
type Tally struct {
	Count int64
}

// TallySchema reads it.
var TallySchema = schema.Struct[Tally]("Counted",
	schema.FieldOf("count", schema.Int64(),
		func(tally Tally) int64 { return tally.Count },
		func(tally *Tally, value int64) { tally.Count = value }),
)

// Text is a value bound as a statement's argument, so a test and a program
// spell it the same way.
func Text(value string) dynamic.Value {
	return dynamic.OfText(value)
}
